### ISSUE TITLE
Scrollable Scorecard

### ISSUE THREAD

**Issue by lkoehl** [hamvocke/doppelkopf#4]
Right now the scorecard isn't scrollable. After playing multiple rounds the points appear not readable outside of the screen.

**Comment by hamvocke** [comment]
Good catch. The entire scorecard is still pretty messy and needs some love urgently.

Making the scorecard scrollable could be a matter of adding a `overflow-y: scroll;` to the scorecard's CSS.

This is a great candidate for a first pull request. Do you feel like submitting one?

**Comment by hamvocke** [comment]
Closed by #5
