### ISSUE TITLE
Anouncement Bug

### ISSUE THREAD

**Issue by davidkaufmann** [hamvocke/doppelkopf#40]
![announcement_bug_cropped](https://user-images.githubusercontent.com/12951672/103483579-8390fa00-4de8-11eb-81f5-677303ba99ba.png)

Gabriele announced kontra and I had the kontra dropdown open, announcing only milliseconds later.
To be honest I don't remember if we got an extra point (don't think so), but announcing twice shouldn't be possible by game logic.

**Comment by hamvocke** [comment]
That's right. If your party already announced something, `possibleAnnouncements()` should only return announcements that haven't been made by any player of your party. Currently it's only looking at your own announcements, which is not enough.
