### ISSUE TITLE
building docker: COPY dist/ /var/www ERROR: Service 'webserver' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder832339339/dist: no such file or directory

### ISSUE THREAD

**Issue by davidh38** [hamvocke/doppelkopf#47]
When i build the docker, i get an error in ubuntu 20.04:
in the backend directory i type:
docker-compose build

after that i get the following error:

Building webserver
Step 1/7 : FROM caddy:2-alpine
 ---> 2c73dc9258a8
Step 2/7 : COPY dist/ /var/www
ERROR: Service 'webserver' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder832339339/dist: no such file or directory

**Comment by hamvocke** [comment]
Looks like there's no `dist/` directory on your machine.

Within the `frontend/` directory, run `yarn build` to build the frontend application. This will create the `dist/` directory and `docker-compose build` can then pick it up and copy the `dist/` directory into the docker image.

If you're just looking for the ready-built docker images, you can also find them on Docker Hub:

* [frontend application](https://hub.docker.com/r/hamvocke/doppelkopf-web) - if you just want to run the game itself somewhere, this image should be all you need
* [backend application](https://hub.docker.com/r/hamvocke/doppelkopf-backend)

The images will be built and published with every commit to master (which is quite frequently) and I never bothered to tag them according to any versioning scheme. So you will always end up with the `latest` version this way.
