### ISSUE TITLE
Multiplayer mode

### ISSUE THREAD

**Issue by hamvocke** [hamvocke/doppelkopf#62]
_Not an issue, but an update/announcement._

For the past few months I've tried building a multiplayer mode into the existing game. I started with [a spike](https://github.com/hamvocke/multiplayer-spike) back in December 2020 - which confirmed my original (and naive) idea that it'd be possible to retrofit a multiplayer mode into this game _somehow_. As someone who's completely new to building multiplayer game servers, this spike validated a few initial assumptions around the tech stack (a JS front end, socket.io and a Flask backend) and the flow it'd take to establish a multiplayer game (establishing connections, joining game rooms, dispatching messages, handling disconnects/reconnects).

The following months I've tried bringing multiplayer into this code base. And while I made _some_ progress over the last few months, today I'm officially announcing that I **will not continue** working on a multiplayer mode for this code base.

### Why?
There's a few main reasons why I'm stopping multiplayer development

1. The progress I've made is far from where I want it to be. I keep running in circles when it comes to establishing and maintaining a server connection and doing it in a resilient way.
2. Working on a multiplayer mode (in this code base) seems to be hard on the schedule I can dedicate to this project. I've got one or two hours here and there that I am willing and able to spend on this code base. That's not enough to keep your head wrapped around complex set up flows and as a consequence I find myself rebuilding the same mental context over and over and over again whenever I want to tackle the next step. Even TDD doesn't seem to help here.
3. Singleplayer mode development is completely stalling as a consequene. Multiplayer has been grabbing my entire focus (with a short detour to migrating everything to TypeScript).
4. There's an inevitable challenge looming on the horizon (even if we solved the multiplayer setup flow): This game started as a singleplayer game and as a consequence, the entire game logic sits within the clients. While it's possible to build a client-authoritative game server (where one client becomes the leader and determines the "correct" game state) it sucks to build a game server this way. The multiplayer experience will always be lacking since server-side validation can't become a thing unless we get the game logic to the server.

### What did I learn?

That's not to say there's nothing to learn from this experience. I _did_ build a bunch of things that were somewhat working.

![Screenshot 2021-07-31 at 17-06-50 Doppelkopf](https://user-images.githubusercontent.com/491469/127744468-494538d6-cee6-4ee6-95c9-5e070ce3bf82.png)

There's a "lobby" kind of concept (called `waitingRoom` in our code). A player can start a game on the server. The server will create a game room that players can join. The server keeps track of all games, all players and the games that players have joined. The player starting a game can share a link to the game with other players. When opening the link, those players will establish a socket connection and join the right game until the room is full (4 players joined). In the meantime, the `WaitingRoom` component will show who's waiting for the game to start.

### What's next?

1. Short term: I'll remove the multiplayer code (`socketClient.ts`, `multiplayerHandler.ts`, `WaitingRoom.vue`, `waitingRoom.ts` and others) from the code base. I'm even thinking about nuking the _entire_ `backend/` project since it ceases to have any reason to exist. I'll drop all "multiplayer" related tasks from the project backlog.
2. Long-term: This project is supposed to be a singleplayer game and I'll keep it that way. I'd rather do one thing and do it well instead of shoe-horning a half-assed multiplayer solution into a code base that started with a different purpose.
3. Mid-term: I'll play around with the idea of creating a multiplayer game server from scratch. In a new repo, completely outside of this project. This allows me to experiment a bit more and might lead up to a new version of this game in the distant future. Maybe it'll end getting me nowhere. And that's okay.

**Comment by davidkaufmann** [comment]
Reading this got me really devastated at first. Multiplayer was something I was really looking forward to. Doppelkopf is a game that lives through interaction with your fellow gamers. Trying to recreate the game with an AI is not only a hard task, it will never actually feel like playing with (and against) humans. Although I'm having fun and I'm actually making quite some progress on the rule-based AI part, multiplayer would have kinda solved this 😏 

After realising what you've written and going through you're reasoning I must admit it is completely sound.
Maybe you remember in our first encounter I was asking about how a multiplayer could be implemented in javascript. At this point I wasn't actually seeing this happening without rewriting the whole thing - i got kinda excited when you revealed your plans on multiplayer architecture 😄

There is one thing that comes to my mind though which kinda makes sense and actually could work out without having to rewrite much of the game-logic. Why not use express as backend and provide a REST interface. Calling the REST endpoints from Vue (using Vuex?) would probably work out instead of calling the Game objects itself. I haven't gone through this entirely and must admit I pretty much lack the experience to judge if this could work, but it kinda does in my head.
It would even make it possible to pretty much seperate backend from frontend and make node and express exchangeable for something else in a further step. Maybe give it a try, mid-term 😁 

Anyway I'm still very much willing to contribute and if you ever feel like going through some tech stuff just drop me a line 👍🏻

**Comment by hamvocke** [comment]
It is possible to shoehorn a multiplayer mode into the existing game. Spending the past few months trying to do so made me realize that _I_ don't have the time, motivation and energy to pull this off.

The game logic itself can remain largely untouched to support a multiplayer mode. The hard part is handling the communication and infrastructure challenges that arise from a near real-time multiplayer game:

* handling persistent socket connections
* presence detection
* seamlessly restoring socket connections when a server restarts (e.g. when a new version is deployed) or a client reconnects (e,.g. due to bad wifi, closing their browser tab)
* preventing abuse: players sending illegal messages that would ruin the entire game-state. I've completely ignored this problem for starters but it's something we'd eventually have to solve

Using `socket.io` over bare websockets helps with some foundational things (e.g. buffering messages, handling reconnects on a basic level). A bullet-proof presence detection and re-establishing connections over server restarts and client reconnects requires a good bunch of server-side logic and additional persistence (e.g. via Redis). Simply storing socket information in memory doesn't cut it if we don't want to force people to start a new game whenever a new version of the backend is deployed. Some server-side frameworks help with these kinds of problems. Elixir's [Phoenix](https://www.phoenixframework.org/), for example, promises to handle some of the presence detection and persistence problems. There are open source implementations for real-time game servers that offer a convenient way to handle matches, matchmaking, presence, state validation, persistence, etc (e.g. [Nakama](https://github.com/heroiclabs/nakama)). I've considered playing around with either approach, read through the docs, did some very shallow testing and maybe that's something I'll continue to do further down the road. But for now I've decided that I want to stay true to the game's original idea: being a browser-based single player game that helps people learn how to play Doppelkopf.

The game's domain model (everything in the `src/model` directory) is pretty well isolated, so it would be possible to move the entire game logic into a new project that runs the logic server-side. If anyone's interested doing this, I encourage them to do so.

**Comment by HenriWahl** [comment]
@davidkaufmann if you urgently need to play some Doppelkopf online maybe https://github.com/henriwahl/doko3000 can be of use for you. It is multiplayer only and free of any rules - just roll your own. Combined with a video conference system like Jitsi it does not completely replace a real :beer: based card game session but helps a little bit.
